name: Selenium Python Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  selenium-tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: poetry install --no-root
    - name: Restore WebDriver cache
      uses: actions/cache@v3
      with:
        path: drivers_cache
        key: ${{ runner.os }}-webdriver-cache
    - name: 'Create env file'
      run: |
        touch .env
        echo CI=true >> .env
        echo HEADLESS=true >> .env
        echo PARALLEL=false >> .env
        echo LOG_CLI=false >> .env
        echo LOG_LEVEL=CRITICAL >> .env
        cat .env
    - name: Run Selenium tests
      run: poetry run pytest --maxfail=1 --disable-warnings -v
  lint:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: Run linter
        run: poetry run ruff check .
